{% set name = "pyina" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyina-{{ version }}.tar.gz
  sha256: 803a7cec72265419794ef44723b36bbb49cacbe97c48494b75d7f05ca743beea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - cython >=0.29.30
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - dill >=0.4.0
    - pox >=0.3.6
    - pathos >=0.3.4
    - mystic >=0.4.2
    - cython >=0.29.30
    - numpy >=1.0
    - mpi4py >=1.3,!=3.0.2

test:
  commands:
    - export OMPI_MCA_plm_rsh_agent=sh  # [unix]
    - python -c "import pyina"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uqfoundation/pyina
  summary: MPI parallel map and cluster scheduling
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
