{% set name = "pyina" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyina-{{ version }}.tar.gz
  sha256: 18c58c0fb008558d35a0c5769fc68982a9e9541effa1cc4c38212fc0bab9247c

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=42
    - cython >=0.29.30
    - pip
  run:
    - python
    - numpy
    - dill >=0.3.8
    - pox >=0.3.4
    - pathos >=0.3.2
    - mystic >=0.4.2
    - cython >=0.29.30
    - numpy >=1.0
    - mpi4py >=1.3,!=3.0.2

test:
  commands:
    - export OMPI_MCA_plm_rsh_agent=sh  # [unix]
    - python -c "import pyina"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uqfoundation/pyina
  summary: MPI parallel map and cluster scheduling
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
