{% set name = "pyina" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyina-{{ version }}.tar.gz
  sha256: b17fa119cb73b5441b2d56017a4f7c7063b866b61a1ca2fe36a82a061b19a061

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=42
    - cython >=0.29.30
    - numpy
    - dill
    - pathos
    - pox
    - mpi4py
    - pip
  run:
    - python
    - numpy >=1.0
    - dill >=0.3.6
    - pox >=0.3.2
    - pathos >=0.3.0
    - mpi4py >=1.3,!=3.0.2

test:
  commands:
    - export OMPI_MCA_plm_rsh_agent=sh  # [unix]
    - python -c "import pyina"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uqfoundation/pyina
  summary: MPI parallel map and cluster scheduling
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
